# Generated by Django 3.0.3 on 2020-03-13 21:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garbages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('markertype', models.IntegerField()),
                ('full', models.BooleanField(default=False)),
                ('broke', models.BooleanField(default=False)),
                ('missing', models.BooleanField(default=False)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('descr', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/static/photos'), upload_to='')),
            ],
        ),
    ]
