# Generated by Django 3.0.4 on 2020-03-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='username',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AlterField(
            model_name='reports',
            name='descr',
            field=models.TextField(blank=True),
        ),
    ]
