# Generated by Django 3.0.4 on 2020-03-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0002_auto_20200325_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
