# Generated by Django 3.0.4 on 2020-03-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0003_auto_20200327_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
