# Generated by Django 3.0.4 on 2020-05-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0004_auto_20200327_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbages',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
