# Generated by Django 3.1.1 on 2020-09-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0005_garbages_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='SOME STRING', max_length=50)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('markertype', models.IntegerField()),
            ],
        ),
    ]
